# Generated by Django 6.1.2 on 2026-10-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.PositiveIntegerField(default=1)),
                ('ano', models.PositiveSmallIntegerField()),
                ('disciplina', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ano', 'disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ra', models.PositiveBigIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='core.turma')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
